### ISSUE TITLE
Retract v1.0.0

### ISSUE THREAD

**Issue by dentych** [chigopher/pathlib#55]
Hello.

It appears that you have at some point accidentally published a v1.0.0, which is now present in proxy.golang.org and will be downloaded if you `go get github.com/chigopher/pathlib@latest`.

proxy.golang.org adheres to the `retract` directive in `go.mod`. Can you please make a v1.0.1 that retracts v1.0.0+v1.0.1?
Read more here: https://go.dev/ref/mod#go-mod-file-retract

Effectively, people using this plugin and proxy.golang.org will never get updates until this has happened or you decide to release a v1.x.x of this package.

**Comment by LandonTClipp** [comment]
Hi, thanks for the post. Yes that was a mistake that unfortunately went out. I will look into doing the retract like you mentioned. Thanks!

**Comment by hjarrell** [comment]
Hi I am still having this issue with another package that depends on this one. I think its due to the tag for v1.0.0 being missing on github.

```
GO111MODULE=on go install github.com/vektra/mockery/v2
go: downloading github.com/chigopher/pathlib v1.0.0
../../go/pkg/mod/github.com/vektra/mockery/v2@v2.32.4/cmd/mockery.go:13:2: reading github.com/chigopher/pathlib/go.mod at revision v1.0.0: unknown revision v1.0.0
```

And listing the version of this package:

```
go list -m github.com/chigopher/pathlib
go: github.com/chigopher/pathlib@v1.0.0: invalid version: unknown revision v1.0.0
```

I am not a go developer so could be wrong on the root cause.

**Comment by LandonTClipp** [comment]
@hjarrell are you working from within a `go.mod` project? mockery no longer depends on v1.0.0 so it seems like something you're using is out of date.

**Comment by hjarrell** [comment]
You're right I am working in in a go.mod project and it seems the go.sum is pinned to 1.0.0: https://github.com/eksctl-io/eksctl/blob/main/go.sum#L481 . 

`go install` works with that command but `go get` fails. Since this isn't a problem with your package feel free to ignore it but if you have time, is there a different command I could use to update the transient dependency on pathlib?

**Comment by LandonTClipp** [comment]
```
go get -u
go mod tidy
``` 

should work, or just get a specific version of pathlib and it should (?) update your dependency directly.
